---
- name: Download AWS CLI v2 (macOS Intel)
  get_url:
    url: https://awscli.amazonaws.com/AWSCLIV2.pkg
    dest: /tmp/AWSCLIV2.pkg
    mode: '0644'

- name: Install AWS CLI v2 (macOS Intel)
  command: sudo installer -pkg /tmp/AWSCLIV2.pkg -target /