- name: Docker - Install Docker via Homebrew.
  homebrew:
    name: docker
    state: present

- name: Docker - Warning about Docker Desktop.
  debug:
    msg: "Docker Desktop installation must be done manually on macOS Catalina."
