---
- name: Include tasks for Ubuntu.
  include_tasks: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- name: Include tasks for macOS Catalina.
  include_tasks: macos.yml
  when: ansible_facts['system'] == 'Darwin' and ansible_facts['distribution_version'] is search('10.15')