---
- name: Install network tools.
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  with_items:
    - net-tools
    - whois
    - iputils-ping
    - dnsutils
    - traceroute
    - tcpdump
    - rdesktop
    - nmap