---
- name: Update repo and cache.
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install network tools.
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - net-tools
    - whois
    - iputils-ping
    - dnsutils
    - traceroute
    - tcpdump
    - rdesktop
    - nmap