---
- name: Ensure /etc/apt/keyrings exists.
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Remove any old VSCode repo definitions.
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/apt/sources.list.d/vscode.list
    - /etc/apt/sources.list.d/vscode.sources
    - /etc/apt/sources.list.d/code.list

- name: Remove any old Microsoft keyrings and trusted keys.
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /usr/share/keyrings/microsoft.gpg
    - /etc/apt/trusted.gpg.d/microsoft.gpg

- name: Download VSCode GPG key and convert to binary format.
  shell: |
    curl -fsSL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor -o /etc/apt/keyrings/microsoft.gpg
  args:
    creates: /etc/apt/keyrings/microsoft.gpg

- name: Add VSCode repository.
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/microsoft.gpg] https://packages.microsoft.com/repos/code stable main"
    state: present
    filename: vscode

- name: Install VSCode.
  apt:
    name: code
    state: present
