---
- name: Set real user (not root).
  set_fact:
    real_user: "{{ ansible_env.SUDO_USER | default(ansible_user_id) }}"

- name: Check existing kubectl.
  stat:
    path: /usr/local/bin/kubectl
    follow: false
  register: kubectl_stat

- name: Remove /usr/local/bin/kubectl if it is a symlink.
  file:
    path: /usr/local/bin/kubectl
    state: absent
  when: kubectl_stat.stat.islnk | default(false)

- name: Download kubectl (desired version).
  get_url:
    url: "https://s3.us-west-2.amazonaws.com/amazon-eks/{{ kubectl_version }}/bin/darwin/amd64/kubectl"
    dest: "/usr/local/bin/kubectl"
    mode: '0755'
    owner: "{{ real_user }}"
  vars:
    kubectl_version: "1.33.3/2025-08-03"

- name: Verify if kubectl is installed correctly.
  command: kubectl version --client
  register: kubectl_version_output
  changed_when: false

- name: Show kubectl version.
  debug:
    var: kubectl_version_output.stdout

- name: Install packages via Homebrew.
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  become: false
  loop:
    - kubectx
    - kubens
    - kube-score
    - kube-capacity
    - stern