---

- name: Search for macOS updates
  ansible.builtin.command: softwareupdate -l
  register: updates_list

- name: Apply all available updates
  ansible.builtin.command: softwareupdate -ia

- name: Install Homebrew on macOS
  community.general.homebrew:
    name: homebrew
    state: present