---

- name: Search for macOS updates
  ansible.builtin.command: softwareupdate -l
  register: updates_list

- name: Apply all available updates
  ansible.builtin.command: softwareupdate -ia

- name: Install Homebrew on macOS (if not exists)
  ansible.builtin.shell: |
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  args:
    creates: /opt/homebrew/bin/brew
  become: false