---
- name: Update repo and cache.
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Upgrade all packages.
  apt:
    name: "*"
    state: latest

- name: Install packages.
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - curl
    - wget
    - git
    - tree
    - vim
    - screen
    - unzip
    - make
    - jq
    - flameshot
    - kazam
    - tilix
    - zsh

- name: Set real user (not root).
  set_fact:
    real_user: "{{ ansible_env.SUDO_USER | default(ansible_user_id) }}"

- name: Set Zsh as default shell for real user
  become: true
  user:
    name: "{{ real_user }}"
    shell: /usr/bin/zsh

- name: Install Oh My Zsh for real user (if not exists).
  become: true
  become_user: "{{ real_user }}"
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
  args:
    executable: /bin/bash
    creates: "/home/{{ real_user }}/.oh-my-zsh"

- name: Install plugin zsh-autosuggestions.
  become: false
  become_user: "{{ real_user }}"
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: "/home/{{ real_user }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
    version: master

- name: Activate plugin zsh-autosuggestions in .zshrc.
  become: false
  become_user: "{{ real_user }}"
  lineinfile:
    path: "/home/{{ real_user }}/.zshrc"
    regexp: '^plugins='
    line: 'plugins=(git zsh-autosuggestions)'

- name: Install packages via snap.
  snap:
    name: "{{ item }}"
    state: present
  with_items:
    - slack
    - postman

- name: Ensure /etc/apt/keyrings exists
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Google Chrome GPG key
  get_url:
    url: https://dl.google.com/linux/linux_signing_key.pub
    dest: /etc/apt/keyrings/google-chrome.asc
    mode: '0644'

- name: Remove old Google Chrome repository file if exists
  file:
    path: /etc/apt/sources.list.d/google-chrome.list
    state: absent

- name: Add Google Chrome repository
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/google-chrome.asc] http://dl.google.com/linux/chrome/deb stable main"
    state: present
    filename: google-chrome

- name: Install Google Chrome
  apt:
    name: google-chrome-stable
    state: present
    update_cache: yes