---
- name: Include tasks for Ubuntu 22.04
  include_tasks: ubuntu_22.yml
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version is version('22.04', '==')

- name: Include tasks for Ubuntu 24.04
  include_tasks: ubuntu_24.yml
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version is version('24.04', '==')

- name: Include tasks for macOS Catalina
  include_tasks: macos.yml
  when: ansible_facts['system'] == 'Darwin' and ansible_facts['distribution_version'] is search('10.15')